/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */
import org.springframework.boot.gradle.tasks.run.BootRun

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.springframework.boot") version "3.0.6"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-devtools:3.0.2")
    implementation("org.springframework.boot:spring-boot-configuration-processor:3.0.2")
    implementation("org.springframework.boot:spring-boot-starter-actuator:3.0.2")
    implementation("org.springframework.cloud:spring-cloud-starter-circuitbreaker-reactor-resilience4j:3.0.0")
    implementation("org.springframework.cloud:spring-cloud-starter-config:4.0.1")
    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:4.0.0")
    implementation("org.springframework.cloud:spring-cloud-starter-gateway:4.0.1")
    implementation("org.jolokia:jolokia-core:1.7.1")
    implementation("io.micrometer:micrometer-registry-prometheus:1.10.3")
    implementation("io.github.resilience4j:resilience4j-micrometer:2.0.2")
    implementation("io.opentelemetry:opentelemetry-exporter-zipkin:1.19.0")
    implementation("org.webjars:angularjs:1.8.2")
    implementation("org.webjars:jquery:3.6.0")
    implementation("org.webjars:bootstrap:3.3.7-1")
    implementation("org.webjars:angular-ui-router:1.0.20")
    implementation("org.webjars:webjars-locator-core:0.52")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.10.0")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    implementation("com.google.code.gson:gson:2.10.1")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("org.springframework.samples.petclinic.api.ApiGatewayApplication")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.named<BootRun>("bootRun") {
}
