name: Build Gradle project (spring-petclinic-api-gateway)
on:
  push:
    paths:
      - spring-petclinic-api-gateway/**
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: cd spring-petclinic-api-gateway;./gradlew bootBuildImage spring-petclinic-api-gateway