name: Build Gradle project (spring-petclinic-customers-service)
on:
  push:
    paths:
      - spring-petclinic-customers-service/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          build-root-directory: spring-petclinic-customers-service
          arguments: bootBuildImage  --imageName ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic-customers-service:${{ github.sha }}

      - name: Push to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic-customers-service:${{ github.sha }}

